services:
  - type: web
    name: potato-disease-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.10.13